name: terminal
description: The launcher app for Scintilla.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '3.7.3'
dependencies:
  flutter:
    sdk: flutter
  flutter_pty: 0.3.1
  xterm: 3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
